### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by yegor256** [yegor256/curiost#1]
Let's create it

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/yegor256/curiost/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `yegor256/curiost` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `yegor256/curiost` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
